# Generated by Django 5.0.7 on 2024-08-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinonuggies',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
